### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by PhantomRay** [wesleytabaka/rpi-led-matrix-painter#13]
Hi there, 
When running `rpi-led-matrix-painter-examples`, I noticed that it the CPU usage is considerably higher then `kitchen-sink`.

Any thoughts on how to reduce the cpu usage?

**Comment by wesleytabaka** [comment]
Hi @PhantomRay ,

You can definitely change the interval at which we call the paint() method.  It's currently 5ms which is kind of ridiculous.  I guess 33 would be more reasonable.  Even 100 would still give you 10 fps.  It depends on the refresh rate you're going for.

Going from 5 ms to 33 ms I do see a reduction in CPU usage, but still not quite as good as the kitchen-sink example from the rpi-led-matrix library.  100ms seems to be fairly close.

https://github.com/wesleytabaka/rpi-led-matrix-painter-example/blob/8c758bb8d648c54ca3206c6075f17b852b69f463/src/index.ts#L312

Hope this helps!
